# Generated by Django 3.1.7 on 2021-04-09 18:00

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Название")),
                ("phone", models.TextField(verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.CreateModel(
            name="Font",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Наименование")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("b", "Жирный"),
                            ("i", "Курсив"),
                            ("st", "Обычный"),
                            ("bi", "Полужирный курсив"),
                        ],
                        max_length=2,
                        verbose_name="Тип шрифта",
                    ),
                ),
                ("size", models.IntegerField(verbose_name="Размер")),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", max_length=18, verbose_name="Цвет"
                    ),
                ),
            ],
            options={
                "verbose_name": "Шрифт",
                "verbose_name_plural": "Шрифты",
            },
        ),
        migrations.CreateModel(
            name="Paragraph",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "line_spacing",
                    models.FloatField(verbose_name="Межстрочный интервал"),
                ),
                ("aligment", models.IntegerField(verbose_name="Выравнивание")),
                ("space", models.FloatField(verbose_name="Отступ")),
            ],
            options={
                "verbose_name": "Абзац",
                "verbose_name_plural": "Абзацы",
            },
        ),
        migrations.CreateModel(
            name="DocFormat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indexing", models.IntegerField(verbose_name="Нуменрация страниц")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docx_recognizer.company",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "font",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docx_recognizer.font",
                        verbose_name="Шрифт",
                    ),
                ),
                (
                    "paragraph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="docx_recognizer.paragraph",
                        verbose_name="Абзац",
                    ),
                ),
            ],
            options={
                "verbose_name": "Документ",
                "verbose_name_plural": "Документы",
            },
        ),
    ]
