# Generated by Django 3.1.7 on 2021-04-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docx_recognizer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="aligment",
            field=models.CharField(
                choices=[
                    ("w", "По ширине"),
                    ("c", "По центру"),
                    ("rb", "По правому краю"),
                    ("lb", "По левому краю"),
                ],
                max_length=2,
                verbose_name="Выравнивание",
            ),
        ),
    ]
