# Generated by Django 3.1.7 on 2021-04-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docx_recognizer", "0002_auto_20210409_2111"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docformat",
            name="indexing",
            field=models.BooleanField(verbose_name="Нуменрация страниц"),
        ),
    ]
