# Generated by Django 3.1.7 on 2021-04-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docx_recognizer", "0005_auto_20210409_2153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paragraph",
            name="aligment",
            field=models.TextField(
                choices=[
                    ("JUSTIFY", "По ширине"),
                    ("CENTER", "По центру"),
                    ("RIGHT", "По правому краю"),
                    ("LEFT", "По левому краю"),
                ],
                verbose_name="Выравнивание",
            ),
        ),
    ]
