# Generated by Django 3.1.7 on 2021-05-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docx_recognizer", "0006_auto_20210409_2207"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paragraph",
            name="space",
        ),
        migrations.AddField(
            model_name="paragraph",
            name="first_line_indent",
            field=models.FloatField(
                default=0, verbose_name="Отступ первой строки абзаца"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paragraph",
            name="left_indent",
            field=models.FloatField(default=0, verbose_name="Отступ слева"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paragraph",
            name="right_indent",
            field=models.FloatField(default=0, verbose_name="Отступ справа"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paragraph",
            name="space_after",
            field=models.FloatField(default=0, verbose_name="Отступ после"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paragraph",
            name="space_before",
            field=models.FloatField(default=0, verbose_name="Отступ до"),
            preserve_default=False,
        ),
    ]
