# Generated by Django 3.1.7 on 2021-05-10 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docx_recognizer", "0008_auto_20210510_2030"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Тип задания")),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="task_type_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="docx_recognizer.tasktype",
                verbose_name="Тип задания",
            ),
            preserve_default=False,
        ),
    ]
