# Generated by Django 3.1.7 on 2021-05-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docx_recognizer", "0010_auto_20210513_2153"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paragraph",
            name="space_after",
        ),
        migrations.RemoveField(
            model_name="paragraph",
            name="space_before",
        ),
        migrations.AlterField(
            model_name="fields",
            name="right",
            field=models.TextField(verbose_name="Правое"),
        ),
    ]
