# Generated by Django 3.1.7 on 2021-05-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docx_recognizer", "0012_remove_docformat_indexing"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="example",
            field=models.FileField(
                null=True, upload_to="media/examples/", verbose_name="Примеры работ"
            ),
        ),
    ]
