# Generated by Django 3.1.7 on 2021-05-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("docx_recognizer", "0015_auto_20210515_1850"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="example_pdf",
        ),
    ]
