# Generated by Django 3.1.7 on 2021-05-18 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docx_recognizer", "0018_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="result",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="docx_recognizer.student",
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="result_docx",
            field=models.FileField(
                upload_to="results/", verbose_name="Результат в виде docx"
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="result_pdf",
            field=models.FileField(
                upload_to="results/", verbose_name="Результат в виде pdf"
            ),
        ),
    ]
