# Generated by Django 3.1.7 on 2021-05-18 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docx_recognizer", "0019_auto_20210518_1941"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.RenameField(
            model_name="paragraph",
            old_name="aligment",
            new_name="alignment",
        ),
        migrations.RemoveField(
            model_name="font",
            name="color",
        ),
        migrations.AddField(
            model_name="docformat",
            name="fields",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="docx_recognizer.fields",
                verbose_name="Поля",
            ),
        ),
    ]
