# Generated by Django 3.1.7 on 2021-05-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docx_recognizer', '0020_auto_20210518_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='bottom',
            field=models.FloatField(verbose_name='Нижнее'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='left',
            field=models.FloatField(verbose_name='Левое'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='right',
            field=models.FloatField(verbose_name='Правое'),
        ),
        migrations.AlterField(
            model_name='fields',
            name='top',
            field=models.FloatField(verbose_name='Верхнее'),
        ),
    ]
